"""empty message

Revision ID: 9dd167f162ab
Revises: 
Create Date: 2020-11-29 12:40:48.685178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dd167f162ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teste')
    op.alter_column('item_venda', 'id_venda',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('sale', 'date',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'date',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('item_venda', 'id_venda',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_table('teste',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
