"""empty message

Revision ID: f6129e7f8664
Revises: 
Create Date: 2020-09-26 11:50:44.798904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6129e7f8664'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_pizza', sa.String(length=40), nullable=True),
    sa.Column('product_drink', sa.String(length=40), nullable=True),
    sa.Column('qtd_pizza', sa.Integer(), nullable=True),
    sa.Column('qtd_drink', sa.Integer(), nullable=True),
    sa.Column('price_pizza', sa.Float(), nullable=True),
    sa.Column('price_drink', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('menu')
    # ### end Alembic commands ###
